name: ESG Pipeline
on:
  schedule: [{ cron: "0 3 * * *" }]   # daily 03:00 UTC
  workflow_dispatch: {}
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - run: python orchestrate.py
        env:
          DB_URL: ${{ secrets.DB_URL }}           # mysql+mysqlconnector://user:pass@host/db
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }} # if using GenAI
